import { DatabaseService } from '../database/DatabaseService.js';
import { app, dialog } from 'electron';
import path from 'path';
import fs from 'fs';

/**
 * DataArchiveService - Data Export & Archival System
 * Exports transactions, ledgers, and movements to CSV format
 * Allows deletion of archived records to free space
 */
class DataArchiveService {
  constructor() {
    this.db = DatabaseService.getInstance();
  }

  /**
   * Get archive-ready data summary
   * Returns counts of data that can be exported/archived
   */
  async getArchiveSummary() {
    try {
      console.log('[DataArchiveService] Getting archive summary...');

      // Get transaction counts
      const transactions = await this.db.query(`
        SELECT 
          COUNT(*) as total,
          SUM(CASE WHEN transaction_type IN ('buy', 'sell') THEN 1 ELSE 0 END) as farmer_transactions,
          SUM(CASE WHEN transaction_type = 'delivery' THEN 1 ELSE 0 END) as company_transactions,
          SUM(CASE WHEN transaction_type = 'purchase' THEN 1 ELSE 0 END) as dealer_transactions,
          MIN(transaction_date) as oldest_date,
          MAX(transaction_date) as newest_date
        FROM Transactions
      `);

      // Get ledger entry counts
      const ledgerEntries = await this.db.query(`
        SELECT 
          COUNT(*) as total,
          SUM(CASE WHEN entity_type = 'farmer' THEN 1 ELSE 0 END) as farmer_ledgers,
          SUM(CASE WHEN entity_type = 'company' THEN 1 ELSE 0 END) as company_ledgers,
          SUM(CASE WHEN entity_type = 'dealer' THEN 1 ELSE 0 END) as dealer_ledgers
        FROM LedgerEntries
      `);

      // Get stock movement counts
      const movements = await this.db.query(`
        SELECT 
          COUNT(*) as total,
          SUM(CASE WHEN movement_type = 'IN' THEN 1 ELSE 0 END) as stock_in,
          SUM(CASE WHEN movement_type = 'OUT' THEN 1 ELSE 0 END) as stock_out,
          SUM(CASE WHEN movement_type = 'ADJUSTMENT' THEN 1 ELSE 0 END) as adjustments,
          MIN(movement_date) as oldest_date,
          MAX(movement_date) as newest_date
        FROM StockMovements
      `);

      return {
        success: true,
        data: {
          transactions: transactions[0] || { total: 0 },
          ledgerEntries: ledgerEntries[0] || { total: 0 },
          movements: movements[0] || { total: 0 }
        }
      };
    } catch (error) {
      console.error('[DataArchiveService] Error getting archive summary:', error);
      return { success: false, message: error.message };
    }
  }

  /**
   * Export all data to CSV file
   * Creates a comprehensive CSV with all transactions, ledgers, and movements
   */
  async exportToCSV(filePath, options = {}) {
    try {
      console.log('[DataArchiveService] Exporting data to CSV:', filePath);

      const { dateFrom, dateTo, includeTransactions = true, includeLedgers = true, includeMovements = true } = options;

      let csvContent = '';
      const timestamp = new Date().toISOString();
      const exportedIds = {
        transactionIds: [],
        ledgerIds: [],
        movementIds: []
      };

      // ========== HEADER SECTION ==========
      csvContent += `"AGRICULTURAL INVENTORY MANAGEMENT SYSTEM - DATA ARCHIVE"\n`;
      csvContent += `"Export Date","${timestamp}"\n`;
      csvContent += `"Generated By","System Export"\n`;
      csvContent += `\n`;

      // ========== TRANSACTIONS SECTION ==========
      if (includeTransactions) {
        csvContent += `"=== TRANSACTIONS ==="\n`;
        csvContent += `"Transaction ID","Transaction Number","Date","Type","Entity Type","Entity Name","Item Type","Item Name","Quantity","Unit Price","Total Amount","Payment Type","Cash Paid","Credit Amount","Description"\n`;

        let transactionQuery = `
          SELECT 
            t.transaction_id,
            t.transaction_number,
            t.transaction_date,
            t.transaction_type,
            t.entity_type,
            COALESCE(t.entity_name, t.temp_customer_name, 'Unknown') as entity_name,
            t.item_type,
            CASE 
              WHEN t.item_type = 'product' THEN p.product_name
              WHEN t.item_type = 'grain' THEN g.grain_name
              ELSE 'Unknown'
            END as item_name,
            t.quantity,
            t.unit_price,
            t.total_amount,
            t.payment_type,
            t.cash_paid,
            t.credit_amount,
            t.description
          FROM Transactions t
          LEFT JOIN Products p ON t.item_type = 'product' AND t.item_id = p.product_id
          LEFT JOIN GrainTypes g ON t.item_type = 'grain' AND t.item_id = g.grain_id
          WHERE 1=1
        `;
        const params = [];

        if (dateFrom) {
          transactionQuery += ` AND DATE(t.transaction_date) >= ?`;
          params.push(dateFrom);
        }
        if (dateTo) {
          transactionQuery += ` AND DATE(t.transaction_date) <= ?`;
          params.push(dateTo);
        }

        transactionQuery += ` ORDER BY t.transaction_date DESC`;

        const transactions = await this.db.query(transactionQuery, params);

        for (const t of transactions) {
          exportedIds.transactionIds.push(t.transaction_id);
          csvContent += `"${t.transaction_id}","${t.transaction_number || ''}","${t.transaction_date || ''}","${t.transaction_type || ''}","${t.entity_type || ''}","${this.escapeCSV(t.entity_name)}","${t.item_type || ''}","${this.escapeCSV(t.item_name)}","${t.quantity || 0}","${t.unit_price || 0}","${t.total_amount || 0}","${t.payment_type || ''}","${t.cash_paid || 0}","${t.credit_amount || 0}","${this.escapeCSV(t.description)}"\n`;
        }

        csvContent += `"Total Transactions","${transactions.length}"\n`;
        csvContent += `\n`;
      }

      // ========== FARMER LEDGER SECTION ==========
      if (includeLedgers) {
        csvContent += `"=== FARMER LEDGER ENTRIES ==="\n`;
        csvContent += `"Entry ID","Entry Date","Farmer ID","Farmer Name","Transaction Type","Description","Debit","Credit","Balance","Transaction ID"\n`;

        let farmerLedgerQuery = `
          SELECT 
            le.entry_id,
            le.entry_date,
            le.entity_id,
            f.name as entity_name,
            le.transaction_type,
            le.description,
            le.debit,
            le.credit,
            le.balance,
            le.transaction_id
          FROM LedgerEntries le
          LEFT JOIN Farmers f ON le.entity_id = f.farmer_id
          WHERE le.entity_type = 'farmer'
        `;
        const farmerParams = [];

        if (dateFrom) {
          farmerLedgerQuery += ` AND DATE(le.entry_date) >= ?`;
          farmerParams.push(dateFrom);
        }
        if (dateTo) {
          farmerLedgerQuery += ` AND DATE(le.entry_date) <= ?`;
          farmerParams.push(dateTo);
        }

        farmerLedgerQuery += ` ORDER BY le.entry_date DESC`;

        const farmerLedgers = await this.db.query(farmerLedgerQuery, farmerParams);

        for (const le of farmerLedgers) {
          exportedIds.ledgerIds.push(le.entry_id);
          csvContent += `"${le.entry_id}","${le.entry_date || ''}","${le.entity_id || ''}","${this.escapeCSV(le.entity_name)}","${le.transaction_type || ''}","${this.escapeCSV(le.description)}","${le.debit || 0}","${le.credit || 0}","${le.balance || 0}","${le.transaction_id || ''}"\n`;
        }
        csvContent += `"Total Farmer Ledger Entries","${farmerLedgers.length}"\n`;
        csvContent += `\n`;

        // ========== COMPANY LEDGER SECTION ==========
        csvContent += `"=== COMPANY LEDGER ENTRIES ==="\n`;
        csvContent += `"Entry ID","Entry Date","Company ID","Company Name","Transaction Type","Description","Debit","Credit","Balance","Transaction ID"\n`;

        let companyLedgerQuery = `
          SELECT 
            le.entry_id,
            le.entry_date,
            le.entity_id,
            c.company_name as entity_name,
            le.transaction_type,
            le.description,
            le.debit,
            le.credit,
            le.balance,
            le.transaction_id
          FROM LedgerEntries le
          LEFT JOIN Companies c ON le.entity_id = c.company_id
          WHERE le.entity_type = 'company'
        `;
        const companyParams = [];

        if (dateFrom) {
          companyLedgerQuery += ` AND DATE(le.entry_date) >= ?`;
          companyParams.push(dateFrom);
        }
        if (dateTo) {
          companyLedgerQuery += ` AND DATE(le.entry_date) <= ?`;
          companyParams.push(dateTo);
        }

        companyLedgerQuery += ` ORDER BY le.entry_date DESC`;

        const companyLedgers = await this.db.query(companyLedgerQuery, companyParams);

        for (const le of companyLedgers) {
          exportedIds.ledgerIds.push(le.entry_id);
          csvContent += `"${le.entry_id}","${le.entry_date || ''}","${le.entity_id || ''}","${this.escapeCSV(le.entity_name)}","${le.transaction_type || ''}","${this.escapeCSV(le.description)}","${le.debit || 0}","${le.credit || 0}","${le.balance || 0}","${le.transaction_id || ''}"\n`;
        }
        csvContent += `"Total Company Ledger Entries","${companyLedgers.length}"\n`;
        csvContent += `\n`;

        // ========== DEALER LEDGER SECTION ==========
        csvContent += `"=== DEALER LEDGER ENTRIES ==="\n`;
        csvContent += `"Entry ID","Entry Date","Dealer ID","Dealer Name","Transaction Type","Description","Debit","Credit","Balance","Transaction ID"\n`;

        let dealerLedgerQuery = `
          SELECT 
            le.entry_id,
            le.entry_date,
            le.entity_id,
            d.name as entity_name,
            le.transaction_type,
            le.description,
            le.debit,
            le.credit,
            le.balance,
            le.transaction_id
          FROM LedgerEntries le
          LEFT JOIN Dealers d ON le.entity_id = d.dealer_id
          WHERE le.entity_type = 'dealer'
        `;
        const dealerParams = [];

        if (dateFrom) {
          dealerLedgerQuery += ` AND DATE(le.entry_date) >= ?`;
          dealerParams.push(dateFrom);
        }
        if (dateTo) {
          dealerLedgerQuery += ` AND DATE(le.entry_date) <= ?`;
          dealerParams.push(dateTo);
        }

        dealerLedgerQuery += ` ORDER BY le.entry_date DESC`;

        const dealerLedgers = await this.db.query(dealerLedgerQuery, dealerParams);

        for (const le of dealerLedgers) {
          exportedIds.ledgerIds.push(le.entry_id);
          csvContent += `"${le.entry_id}","${le.entry_date || ''}","${le.entity_id || ''}","${this.escapeCSV(le.entity_name)}","${le.transaction_type || ''}","${this.escapeCSV(le.description)}","${le.debit || 0}","${le.credit || 0}","${le.balance || 0}","${le.transaction_id || ''}"\n`;
        }
        csvContent += `"Total Dealer Ledger Entries","${dealerLedgers.length}"\n`;
        csvContent += `\n`;
      }

      // ========== STOCK MOVEMENTS SECTION ==========
      if (includeMovements) {
        csvContent += `"=== STOCK MOVEMENTS ==="\n`;
        csvContent += `"Movement ID","Movement Date","Stock ID","Item Type","Item Name","Movement Type","Reason","Quantity","Unit Price","Previous Qty","New Qty","Reference Type","Reference ID","Notes"\n`;

        let movementQuery = `
          SELECT 
            sm.movement_id,
            sm.movement_date,
            sm.stock_id,
            s.item_type,
            CASE 
              WHEN s.item_type = 'PRODUCT' THEN p.product_name
              WHEN s.item_type = 'GRAIN' THEN g.grain_name
              ELSE 'Unknown'
            END as item_name,
            sm.movement_type,
            sm.movement_reason,
            sm.quantity,
            sm.unit_price,
            sm.previous_quantity,
            sm.new_quantity,
            sm.reference_type,
            sm.reference_id,
            sm.notes
          FROM StockMovements sm
          LEFT JOIN Stock s ON sm.stock_id = s.stock_id
          LEFT JOIN Products p ON s.item_type = 'PRODUCT' AND s.item_id = p.product_id
          LEFT JOIN GrainTypes g ON s.item_type = 'GRAIN' AND s.item_id = g.grain_id
          WHERE 1=1
        `;
        const movementParams = [];

        if (dateFrom) {
          movementQuery += ` AND DATE(sm.movement_date) >= ?`;
          movementParams.push(dateFrom);
        }
        if (dateTo) {
          movementQuery += ` AND DATE(sm.movement_date) <= ?`;
          movementParams.push(dateTo);
        }

        movementQuery += ` ORDER BY sm.movement_date DESC`;

        const movements = await this.db.query(movementQuery, movementParams);

        for (const m of movements) {
          exportedIds.movementIds.push(m.movement_id);
          csvContent += `"${m.movement_id}","${m.movement_date || ''}","${m.stock_id || ''}","${m.item_type || ''}","${this.escapeCSV(m.item_name)}","${m.movement_type || ''}","${m.movement_reason || ''}","${m.quantity || 0}","${m.unit_price || 0}","${m.previous_quantity || 0}","${m.new_quantity || 0}","${m.reference_type || ''}","${m.reference_id || ''}","${this.escapeCSV(m.notes)}"\n`;
        }
        csvContent += `"Total Stock Movements","${movements.length}"\n`;
        csvContent += `\n`;
      }

      // ========== SUMMARY SECTION ==========
      csvContent += `"=== EXPORT SUMMARY ==="\n`;
      csvContent += `"Total Transactions Exported","${exportedIds.transactionIds.length}"\n`;
      csvContent += `"Total Ledger Entries Exported","${exportedIds.ledgerIds.length}"\n`;
      csvContent += `"Total Stock Movements Exported","${exportedIds.movementIds.length}"\n`;
      csvContent += `"Export Completed","${new Date().toISOString()}"\n`;

      // Write to file
      fs.writeFileSync(filePath, csvContent, 'utf8');

      console.log('[DataArchiveService] ✅ CSV export completed:', filePath);

      return {
        success: true,
        message: 'Data exported successfully',
        data: {
          filePath,
          exportedIds,
          counts: {
            transactions: exportedIds.transactionIds.length,
            ledgerEntries: exportedIds.ledgerIds.length,
            movements: exportedIds.movementIds.length
          }
        }
      };
    } catch (error) {
      console.error('[DataArchiveService] Error exporting to CSV:', error);
      return { success: false, message: error.message };
    }
  }

  /**
   * Delete archived records after export
   * Only deletes records that have been exported
   */
  async deleteArchivedData(options = {}) {
    try {
      console.log('[DataArchiveService] Deleting archived data...');

      const { 
        transactionIds = [], 
        ledgerIds = [], 
        movementIds = [],
        deleteTransactions = false,
        deleteLedgers = false,
        deleteMovements = false
      } = options;

      let deletedCounts = {
        transactions: 0,
        ledgerEntries: 0,
        movements: 0
      };

      // Begin transaction
      await this.db.execute('BEGIN TRANSACTION');

      try {
        // Delete transactions
        if (deleteTransactions && transactionIds.length > 0) {
          // First delete transaction items
          const placeholders = transactionIds.map(() => '?').join(',');
          await this.db.execute(
            `DELETE FROM TransactionItems WHERE transaction_id IN (${placeholders})`,
            transactionIds
          );
          
          const result = await this.db.execute(
            `DELETE FROM Transactions WHERE transaction_id IN (${placeholders})`,
            transactionIds
          );
          deletedCounts.transactions = result.changes || transactionIds.length;
        }

        // Delete ledger entries
        if (deleteLedgers && ledgerIds.length > 0) {
          const placeholders = ledgerIds.map(() => '?').join(',');
          const result = await this.db.execute(
            `DELETE FROM LedgerEntries WHERE entry_id IN (${placeholders})`,
            ledgerIds
          );
          deletedCounts.ledgerEntries = result.changes || ledgerIds.length;
        }

        // Delete stock movements
        if (deleteMovements && movementIds.length > 0) {
          const placeholders = movementIds.map(() => '?').join(',');
          const result = await this.db.execute(
            `DELETE FROM StockMovements WHERE movement_id IN (${placeholders})`,
            movementIds
          );
          deletedCounts.movements = result.changes || movementIds.length;
        }

        // Commit transaction
        await this.db.execute('COMMIT');

        console.log('[DataArchiveService] ✅ Archived data deleted:', deletedCounts);

        return {
          success: true,
          message: 'Archived data deleted successfully',
          data: deletedCounts
        };
      } catch (error) {
        await this.db.execute('ROLLBACK');
        throw error;
      }
    } catch (error) {
      console.error('[DataArchiveService] Error deleting archived data:', error);
      return { success: false, message: error.message };
    }
  }

  /**
   * Delete data by date range
   * Deletes all transactions, ledgers, and movements within the date range
   */
  async deleteDataByDateRange(dateFrom, dateTo, options = {}) {
    try {
      console.log('[DataArchiveService] Deleting data by date range:', dateFrom, 'to', dateTo);

      const { 
        deleteTransactions = false,
        deleteLedgers = false,
        deleteMovements = false
      } = options;

      let deletedCounts = {
        transactions: 0,
        ledgerEntries: 0,
        movements: 0
      };

      // Begin transaction
      await this.db.execute('BEGIN TRANSACTION');

      try {
        // Delete transactions in date range
        if (deleteTransactions) {
          // First get transaction IDs to delete transaction items
          const transactions = await this.db.query(
            `SELECT transaction_id FROM Transactions WHERE DATE(transaction_date) BETWEEN ? AND ?`,
            [dateFrom, dateTo]
          );
          const txIds = transactions.map(t => t.transaction_id);
          
          if (txIds.length > 0) {
            const placeholders = txIds.map(() => '?').join(',');
            await this.db.execute(
              `DELETE FROM TransactionItems WHERE transaction_id IN (${placeholders})`,
              txIds
            );
          }
          
          const result = await this.db.execute(
            `DELETE FROM Transactions WHERE DATE(transaction_date) BETWEEN ? AND ?`,
            [dateFrom, dateTo]
          );
          deletedCounts.transactions = result.changes || 0;
        }

        // Delete ledger entries in date range
        if (deleteLedgers) {
          const result = await this.db.execute(
            `DELETE FROM LedgerEntries WHERE DATE(entry_date) BETWEEN ? AND ?`,
            [dateFrom, dateTo]
          );
          deletedCounts.ledgerEntries = result.changes || 0;
        }

        // Delete stock movements in date range
        if (deleteMovements) {
          const result = await this.db.execute(
            `DELETE FROM StockMovements WHERE DATE(movement_date) BETWEEN ? AND ?`,
            [dateFrom, dateTo]
          );
          deletedCounts.movements = result.changes || 0;
        }

        // Commit transaction
        await this.db.execute('COMMIT');

        console.log('[DataArchiveService] ✅ Data deleted by date range:', deletedCounts);

        return {
          success: true,
          message: 'Data deleted successfully',
          data: deletedCounts
        };
      } catch (error) {
        await this.db.execute('ROLLBACK');
        throw error;
      }
    } catch (error) {
      console.error('[DataArchiveService] Error deleting data by date range:', error);
      return { success: false, message: error.message };
    }
  }

  /**
   * Escape CSV special characters
   */
  escapeCSV(value) {
    if (value === null || value === undefined) return '';
    const str = String(value);
    // Replace double quotes with two double quotes
    return str.replace(/"/g, '""');
  }
}

export default DataArchiveService;
